@startuml key
salt
title Recipe Entry
{
  {
    {
      "name                 "
      {
        {
          "category"
          "cuisine "
        } | 
        {
          prep: | "  " | ^min^
          cook: | "  " | ^min^
        }
      }
      {+
        description
        .
        "                     "
      }
    } | 
    {
      "image URL             "
      {+
        .
        .
        .                      img
        .
        .
        "                      "
      }
    }
  }
  {
    ingredients section
  }
  {
    instructions section
  }
  {
    nutrition section
  }
}
@enduml