@startuml key
salt
title Recipe Entry
{
  {
    {
      "name                 "
      {
        {
          "category"
          "cuisine "
        } | 
        {
          prep: | "  " | ^min^
          cook: | "  " | ^min^
        }
      }
      {+
        description
        .
        "                     "
      }
      "author label         "
    } | 
    {
      "image URL             "
      {+
        .
        .
        .                      img
        .
        .
        "                      "
      }
      "author link           "
    }
  }
  ==
  {
    Qty | Unit | Ingredient | State (opt)
    "  " | ^unit^ | "                      " | "           " | .
    "  " | ^unit^ | "                      " | "           " | [+]
  }
  ==
  {
     # | Step
    1. | {+
           instructions
           .
           "                                         "
         } | [+]

  }
  ==
  {
    Serving size: | "  " | ^unit^ | . | . | . | . | total servings: | "  "
  }
  {
    ^nutrition element^ | [+]
  }
  {
    [submit]
  }
}
@enduml